import { Product } from "@/types/product";

// bisa ganti ke prisma / db nanti
export async function getProducts(): Promise<Product[]> {
  return [
    {
      id: 1,
      title: "Aikon",
      price: 230000,
      description: "Kamera analog dengan hasil foto klasik",
      category: "analog",
      image: "/image/product1.png",
    },
    {
      id: 2,
      title: "Canon EOS 700D",
      price: 3600000,
      description: "Kamera DSLR entry-level dengan fitur lengkap",
      category: "dslr",
      image: "/image/CanonEOS700D.png",
    },
    {
      id: 3,
      title: "Canon EOS M200",
      price: 6200000,
      description: "Kamera DSLR entry-level dengan fitur lengkap",
      category: "mirrorless",
      image: "/image/canonEOSM200(m).png",
    },
    {
      id: 4,
      title: "Fujifilm Finepix",
      price: 2600000,
      description: "Kamera pocket dengan desain kompak dan ringan",
      category: "digicam",
      image: "/image/fujifilm_finepix.png",
    },
    {
      id: 5,
      title: "Fujifilm X100",
      price: 28500000,
      description: "Kamera mirrorless premium dengan lensa tetap",
      category: "mirrorless",
      image: "/image/fujifilmX100(m).png",
    },
    {
      id: 6,
      title: "Kodak",
      price: 450000,
      description: "Kamera analog dengan hasil foto klasik",
      category: "analog",
      image: "/image/kodak.png",
    },
    {
      id: 7,
      title: "Lucky M560",
      price: 450000,
      description: "Kamera analog dengan hasil foto klasik",
      category: "analog",
      image: "/image/luckyM560.png",
    },
    {
      id: 8,
      title: "Nikon D780",
      price: 29300000,
      description: "Kamera DSLR entry-level dengan fitur lengkap",
      category: "dslr",
      image: "/image/nikonD780.png",
    },
    {
      id: 9,
      title: "Samsung Mv900",
      price: 5900000,
      description: "Kamera pocket dengan desain kompak dan ringan",
      category: "digicam",
      image: "/image/samsungMv900.png",
    },
    {
      id: 10,
      title: "Sbox Spark S8",
      price: 1200000,
      description: "Kamera pocket dengan desain kompak dan ringan",
      category: "digicam",
      image: "/image/Sbox_sparkS8.png",
    },
    {
      id: 11,
      title: "Sony A99",
      price: 21300000,
      description: "Kamera DSLR entry-level dengan fitur lengkap",
      category: "dslr",
      image: "/image/sonyA99.png",
    },
    {
      id: 12,
      title: "Sony A6300",
      price: 10200000,
      description: "Kamera mirrorless premium dengan lensa tetap",
      category: "mirrorless",
      image: "/image/sonyA6300(m).png",
    },
    {
      id: 13,
      title: "Sony W510",
      price: 2900000,
      description: "Kamera pocket dengan desain kompak dan ringan",
      category: "digicam",
      image: "/image/sonyW510.png",
    },
    {
      id: 14,
      title: "Sonny ZV-E10",
      price: 6400000,
      description: "Kamera mirrorless premium dengan lensa tetap",
      category: "mirrorless",
      image: "/image/SonyZV-E10(m).png",
    },
    {
      id: 15,
      title: "Topico",
      price: 200000,
      description: "Kamera analog dengan hasil foto klasik",
      category: "analog",
      image: "/image/topico.png",
    },
  ];
}
